### ISSUE TITLE
Head size model not fitting to ImageView Model

### ISSUE THREAD

**Issue by edwardna1** [miruomoo/HydraGame#3]
![image](https://user-images.githubusercontent.com/77164264/167926485-56543ca6-fde4-488f-b166-51d02f1eca2b.png)
Seems like the image here isn't rendering in my game, and when it is, it is poorly rendered.  Head size 3 and 5 have similar issues as well. Please connect with me if I'm missing anything., thanks.

**Comment by edwardna1** [comment]
#2 indirectly related as well.

**Comment by miruomoo** [comment]
ImageViews are initialized with grid dimensions, I think you have the file open wrongly. Please check controller class.
